<!doctype html>
<!--[if lt IE 7]><html lang="en-us" class="ie6"><![endif]-->
<!--[if IE 7]><html lang="en-us" class="ie7"><![endif]-->
<!--[if IE 8]><html lang="en-us" class="ie8"><![endif]-->
<!--[if IE 9]><html lang="en-us" class="ie9"><![endif]-->
<!--[if (gt IE 9)|!(IE)]><!-->
<html lang="en-us">
<!--<![endif]-->
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=Edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no">
  <pbs:!macro name="metadata" cachetime="1440" cachequalifiers="profile,site,date,category,artno,ItemNr,Params,@pagetype,@StoryId,ISOPublishedDate,Date,Category,ID,ArtNo,@SocialHeadline,@AlternateHeadline,@artTitle,@artSummary,@artImage,@StaffFirstName,@StaffID,@StaffLastName,@StaffJobTitle,@StaffImage,@StaffInfo,@photoTitle,@photoCaption,@photoImg,@dpTitle,@dpDescription,@dpTagline,@dpImg,@dpDate,@dpID,@dpModule,@arTitle,@arAbout,@arImg,@arDate,@arID,@arModule,@rankingsUrl,@rankingsTitle,@rankingsText,@rankingsImage">
  <!--#include virtual="/includes/icons.inc"-->
  <!--#include virtual="/includes/styles.inc"-->
  <!--#include virtual="/includes/scripts.inc"-->
  <!--#include virtual="/includes/services.inc"-->
</head>
<body>
  <!--#include virtual="/includes/omniture.inc"-->
  <!--#include virtual="/global/includes/ads/inter.inc"-->
  <!--#include virtual="/includes/meter.inc"-->
  <!-- #oas_Top -->
  <pbs:macro name="ads-header">
  <div class="container print" style="display:none;"><img class="print-logo" src="https://raw.githubusercontent.com/modernhealthcare/mh-logo/master/mh-logo.gif" alt="Modern Healthcare" style="display:none;"></div>
  <!--#include virtual="/includes/touch-menu.inc"-->
  <header class="header">
    <div class="container">
      <div class="pure-g">
        <div class="pure-u-1">
          <nav class="secondary-nav">
            <!--#include virtual="/includes/global-nav.inc"-->
          </nav>
        </div>
        <div class="clearfix"></div>
        <div class="pure-u-1 pure-u-md-10-24">
          <div class="header-logo">
            <h1 class="logo"><a class="omnitrack" data-omnilocation="hdr" data-omnilink="hdr-logo" href="/">Modern Healthcare</a></h1>
            <h2 class="tagline">The leader in healthcare business news, research &amp; data</h2>
          </div>
        </div>
        <div class="pure-u-1 pure-u-md-7-24">
          <div class="header-search">
            <div class="pure-u-1 account">
              <a class="omnitrack" data-omnilocation="main-nav" data-omnilink="my-account" href="https://home.modernhealthcare.com/clickshare/myhome.do">My account <span class="icon-cog"></span></a>
            </div>
            <form class="pure-form pure-g auto" action="/section/search">
              <div class="pure-u-20-24">
                <input class="pure-input-1 st-search-input" type="text" placeholder="Search Modern Healthcare">
              </div>
              <div class="pure-u-4-24">
                <button class="pure-button st-search-input" type="submit"><span class="icon-search"></span></button>
              </div>
            </form>
          </div>
        </div>
        <div class="pure-u-1 pure-u-md-7-24">
          <div class="issue-container">
            <div class="header-issue">
              <ul class="header-issue-list">
                <li class="first"><a href="/section/magazine">This Week's Issue</a></li>
                <li>&bull;&nbsp;<a class="omnitrack" data-omnilocation="main-nav" data-omnilink="subscribe" href="/section/subscriptions">Subscribe</a></li>
                <li>&bull;&nbsp;<a class="omnitrack" data-omnilocation="main-nav" data-omnilink="advertise" href="/section/advertising">Advertise</a></li>
              </ul>
              <pbs:macro name="subscribe">
            </div>
          </div>
        </div>
      </div>
    </div>
  </header>
  <!--#include virtual="/includes/navigation-menu.inc"-->
  <div class="cleafix"></div>
